"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthPriestProvider } from "@/hooks/useAuthPriest";
import { Toaster } from "sonner";
import { AuthUserProvider } from "@/hooks/useAuthUser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthPriestProvider>
          <AuthUserProvider>
            <main className="flex-1">
              {children}
            </main>
          </AuthUserProvider>
        </AuthPriestProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
